language: java
notifications:
  email:
  - arnab.k@gmail.com
branches:
  only:
  - master
before_install:
- sudo apt-get install gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg
  -d
- cp local.secring.gpg ~/.gnupg/secring.gpg
- cp local.pubring.gpg ~/.gnupg/pubring.gpg
script: mvn clean deploy --settings maven_settings.xml
env:
  global:
  - secure: eIK3Nv84N4hTych+OupM4eSBaybZfKD+mfOa8yPvpWL41m9eTWC3tZq/I9m8SeclloYJu3fdGXIhusMOCi6wJTffoUpizuVgzAcDL+AqC2sl+G3KjEzs95wTybb+5JNVd8Ww3yNAGzt4xYqstueAvNj5ZkuZkUCHtjOpWLVXr2c=
  - secure: IFXXf3dSwxjwMalcGvUIVzE8QgHFumI6730/VcrxJ3XnvjBt7dDSUYBH4yIjQiqryNiBFnSWXVo7ZdjLPPzyp0o5aQJQBCy1WNv5JLll6D7uPPqc9yKh0jrKyYfniztDKjuq2aFBdzvSRuwMllqlWfyqepKQcDIRuz28HtNmc3w=
  - secure: IHidR1JY3QeqxFkvae3zu6ntyZvX9eaNYZkTB/P3qOyFCO98y4tnSobUkEVwtdlgGwSnqyhafaRN/btZpJiEZiUiksuvv9U2IsPuf9Yz5E2FLI/iMHFJCLQYbW3Accs4L6q+Yhhxv5u9d1cRov4JWN+XwTWtKdOuNUtOIP7sWQo=
  - secure: oKzOB2ECSHMMs52Ik2nB7J9UhPEM9MpONBo7OEBDN4VvbgQB7GiV7OZYecn3odMB2v8iu15LBmXSDS9KOP01V79BGO4Dj3fAaDBflNDYBjezIwc6IFWG7dKFgNWJEFIVD4CWxCPySh0b7E9Xqu8KcDgBbqjXccRd+g1gAjGqwTg=
