language: java
jdk:
  - oraclejdk8
notifications:
  email:
  - arnab.k@gmail.com
branches:
  only:
  - master
before_install:
- sudo apt-get install gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg
  -d
- cp local.secring.gpg ~/.gnupg/secring.gpg
- cp local.pubring.gpg ~/.gnupg/pubring.gpg
script: mvn --settings maven_settings.xml clean deploy
env:
  global:
  - secure: fxrZmRXlK5WrcD/zdUNB9mDuBdqEY2jIGH6lE/PepF1fUSJ1wJjfYnGhgyK8GIgTY3017gr6pu+ouKnryc+dUviEGkLHj9pPOCuMOMtmaOm/9wRZzpsyJnxgynUTZTvIqnk/lKxis2flSIu68pl/R5jjx7TidejnMDeRrF7vfLk=
  - secure: qsn9PJiTojvubxcozZrLFf0ZmeqSPesraZ19EncuRlP/EIoUKddg+POL4c78mvmKKjlHBE7EkdK4zy2Dx0zKZ0r9piolqv2xE3LnEbkHtfJxUiXMOboDUOiEbn5geFBX/qXMKR+tdjXfWOLmnS2Wvv3aaFV7vqkiNBJr/KkUn6w=
